### ISSUE TITLE
KeyError, (CenterNet Pytorch)

### ISSUE THREAD

**Issue by Hikaru-Furuta** [NNgen/nngen#32]
### issue

I've tried to load an onnx-model that I had created using a module, "torch.onnx.export", from a ".pth"(Pytorch) model.
The following codes are for these implimentaitions.
Some nodes in my onnx-file couldn't be accepted by 'ng.from_onnx'. For example, 'ConvTranspose' is not supported in NNgen.
As is written on [NNgen's Git](https://github.com/NNgen/nngen), I interpreted this as that existing models should be loaded from torchvision instead of creating onnx-file myself.
Is there any possible ways to use my own onnx-file?

**Converting a pytorch-file into onnx-file**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from lib.models.networks.dlav0 import get_pose_net
from lib.models.model import load_model
import torch.onnx as onnx
import torch
from types import MethodType

def forward(self, x):
	x = self.base(x)
	x = self.dla_up(x[self.first_level:])
	ret = []
	for head in self.heads:
		ret.append(self.__getattr__(head)(x))
	return ret

input = torch.zeros([1, 3, 512, 512])
net = get_pose_net(34, {'hm':2, 'reg':2, 'wh':2})
net.forward = MethodType(forward, net)

load_model(net, '../models/ctdet_coco_dla_2x.pth')
onnx.export(net, input, '../models/ctdet_coco_dla_2x_2.onnx', verbose=True)

#Refered to 'https://github.com/CaoWGG/TensorRT-CenterNet/issues/1'
#Model, 'ctdet_coco_dla_2x.pth', downloaded from 'https://drive.google.com/open?id=1pl_-ael8wERdUREEnaIfqOV_VF2bEVRT'
#Centernet-Model description : https://github.com/xingyizhou/CenterNet
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Loading my own onnx-file.**            (Getting_started.py )
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from __future__ import absolute_import
from __future__ import print_function

import sys
import os

import nngen as ng
import torch
import torchvision

# data types
act_dtype = ng.int16
weight_dtype = ng.int16
bias_dtype = ng.int16
scale_dtype = ng.int16

dtypes = {}
(outputs, placeholders, variables,
 constants, operators) = ng.from_onnx('ctdet_coco_dla_2x.onnx',
                                      value_dtypes=dtypes,
                                      default_placeholder_dtype=act_dtype,
                                      default_variable_dtype=weight_dtype,
                                      default_constant_dtype=weight_dtype,
                                      default_operator_dtype=act_dtype,
                                      default_scale_dtype=scale_dtype,
                                      default_bias_dtype=bias_dtype,
                                      disable_fusion=disable_fusion)



if act_dtype.width > 8:
    act_scale_factor = 128
else:
    act_scale_factor = int(round(2 ** (act_dtype.width - 1) * 0.5))

input_scale_factors = {'act': act_scale_factor}
input_means = {'act': imagenet_mean * act_scale_factor}
input_stds = {'act': imagenet_std * act_scale_factor}

ng.quantize(outputs, input_scale_factors, input_means, input_stds)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Loading my own onnx-file**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@:~/git/nngen/nngen/onnx$ python Getting_started.py 
Traceback (most recent call last):
  File "Getting_started.py", line 19, in <module>
    constants, operators) = ng.from_onnx('ctdet_coco_dla_2x.onnx')#,
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 330, in from_onnx
    visitor.visit(name)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 53, in Relu
    return _act_func(operator.relu, visitor, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 53, in Relu
    return _act_func(operator.relu, visitor, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 29, in _act_func
    act_func=method)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/batchnormalization.py", line 45, in BatchNormalization
    act_func=act_func)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/concat.py", line 17, in Concat
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 53, in Relu
    return _act_func(operator.relu, visitor, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 29, in _act_func
    act_func=method)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/batchnormalization.py", line 45, in BatchNormalization
    act_func=act_func)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/concat.py", line 17, in Concat
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 53, in Relu
    return _act_func(operator.relu, visitor, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 29, in _act_func
    act_func=method)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/batchnormalization.py", line 45, in BatchNormalization
    act_func=act_func)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 148, in visit
    node_op = node_func(self, node)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/concat.py", line 17, in Concat
    src_obj = visitor.visit(src)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_func = _get_func(node.op_type)
  File "/home/user/anaconda3/envs/CenterNet_ONNX/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 76, in _get_func
    return func_map[op_type]
KeyError: 'ConvTranspose'

**Comment by Hikaru-Furuta** [comment]
python examples/darknet_yolov3_tiny/darknet_yolov3_tiny.py 
Traceback (most recent call last):
  File "examples/darknet_yolov3_tiny/darknet_yolov3_tiny.py", line 412, in <module>
    rslt = run(silent=False, verilog_filename='tmp.v')
  File "examples/darknet_yolov3_tiny/darknet_yolov3_tiny.py", line 76, in run
    model = models.Darknet(cfg_filename, img_size).to('cpu')
  File "yolov3/models.py", line 231, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "yolov3/utils/parse_config.py", line 25, in parse_model_cfg
    key, val = line.split("=")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Hikaru-Furuta** [comment]
python nngen/onnx/Getting_started.py 
Traceback (most recent call last):
  File "nngen/onnx/Getting_started.py", line 23, in <module>
    constants, operators) = ng.from_onnx('nngen/onnx/YOLOv3_11/test.onnx')#,
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 329, in from_onnx
    visitor.visit(name)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 21, in Conv
    src_obj = visitor.visit(src)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 65, in LeakyRelu
    return _act_func(op, visitor, node)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/act_func.py", line 37, in _act_func
    src_op = conv.Conv(visitor, src_node, act_func=method)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/onnx/conv.py", line 110, in Conv
    c = operator.conv2d(*args, **kwargs)
  File "/home/nel/anaconda3/envs/Center2/lib/python3.6/site-packages/nngen/operator/conv2d.py", line 326, in __init__
    """'%d' != '%d'""" % (input_shape[-1], filter_shape[-1]))
ValueError: input and filter must have a same input channel length as shape[3]: '512' != '768'
free(): invalid pointer
Aborted (core dumped)

**Comment by Hikaru-Furuta** [comment]
commit 9ed1f7fb83908794aa94d70287d89545d45fe875 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 1c88cd7 944befe
Author: shtaxxx <shta.ky1018@gmail.com>
Date:   Sat Jan 2 03:09:30 2021 +0900

**Comment by Hikaru-Furuta** [comment]
FileNotFoundError: Download the YOLOv3 model using Pytorch, such as 'https://github.com/ultralytics/yolov3'. Then extract it, and rename it as 'yolov3'

Traceback (most recent call last):
  File "darknet_yolov3_tiny.py", line 413, in <module>
    rslt = run(silent=False, verilog_filename='tmp.v')
  File "darknet_yolov3_tiny.py", line 77, in run
    model = models.Darknet(cfg_filename, img_size).to('cpu')
AttributeError: module 'models' has no attribute 'Darknet'

**Comment by Hikaru-Furuta** [comment]
commit 3393a98a5f807aaf7284c0fe746c00aa81e2b1ff (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 8daa69d d0b8085
Author: shtaxxx <shta.ky1018@gmail.com>
Date:   Tue Jul 21 17:06:21 2020 +0900


:/nngen/examples/darknet_yolov3_tiny/yolov3# git show
commit 5d42cc1b9a90e26b0b9bffba61fae93f5d1691b9 (HEAD, tag: v7)
Author: Glenn Jocher <glenn.jocher@ultralytics.com>
Date:   Sat May 2 18:44:31 2020 -0700

    Update README.md

diff --git a/README.md b/README.md
index 0329a13..06a3ecd 100755
--- a/README.md
+++ b/README.md
@@ -155,11 +155,12 @@ Speed: 17.5/2.3/19.9 ms inference/NMS/total per 640x640 image at batch-size 16

**Comment by Hikaru-Furuta** [comment]
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.11.0           py36h06a4308_0  
aiohttp                   3.6.3            py36h7b6447c_0  
alabaster                 0.7.12                   pypi_0    pypi
astunparse                1.6.3                      py_0  
async-timeout             3.0.1                    py36_0  
attrs                     20.3.0             pyhd3eb1b0_0  
babel                     2.9.0                    pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.4                      py36_0  
brotlipy                  0.7.0           py36h27cfd23_1003  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2020.10.14                    0  
cachetools                4.1.1                      py_0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.11.8        py36h06a4308_0  
cffi                      1.14.0           py36h2e261b9_0  
chardet                   3.0.4           py36h06a4308_1003  
click                     7.1.2                      py_0  
cryptography              3.2.1            py36h3c74f83_1  
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
docutils                  0.16                     pypi_0    pypi
expat                     2.2.10               he6710b0_2  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
gast                      0.3.3                      py_0  
glib                      2.63.1               h5a9c865_0  
google-auth               1.23.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.2              pyhd3eb1b0_2  
google-pasta              0.2.0                      py_0  
graphite2                 1.3.14               h23475e2_0  
graphviz                  2.40.1               h21bd128_2  
grpcio                    1.31.0           py36hf8bcb03_0  
h5py                      2.10.0           py36hd6299e0_1  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.6               hb1b8bf9_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
idna_ssl                  1.1.0                    py36_0  
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        2.0.0                      py_1  
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254  
jinja2                    2.11.2                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
keras-preprocessing       1.1.0                      py_1  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.13.0.1             hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.3            py36h06a4308_0  
markupsafe                1.1.1                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
multidict                 4.7.6            py36h7b6447c_1  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.1           py36hfd86e86_0  
nngen                     1.3.1                    pypi_0    pypi
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
oauthlib                  3.1.0                      py_0  
olefile                   0.46                     py36_0  
onnx                      1.6.0                    pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
opt_einsum                3.1.0                      py_0  
packaging                 20.8                     pypi_0    pypi
pango                     1.42.4               h049681c_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.0.1            py36he98fc37_0  
pip                       20.2.4           py36h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
pluggy                    0.13.1                   pypi_0    pypi
ply                       3.11                     pypi_0    pypi
protobuf                  3.13.0.1         py36he6710b0_1  
py                        1.10.0                   pypi_0    pypi
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.20                       py_2  
pygments                  2.7.4                    pypi_0    pypi
pyjwt                     1.7.1                    py36_0  
pyopenssl                 19.1.0             pyhd3eb1b0_1  
pysocks                   1.7.1            py36h06a4308_0  
pytest                    6.2.1                    pypi_0    pypi
pytest-pythonpath         0.7.3                    pypi_0    pypi
python                    3.6.10               hcf32534_1  
python-graphviz           0.14.2                     py_0  
pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
pytz                      2020.5                   pypi_0    pypi
pyverilog                 1.3.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.6                        py_0  
scipy                     1.5.2            py36h0b6359f_0  
setuptools                50.3.1           py36h06a4308_1  
six                       1.15.0           py36h06a4308_0  
snowballstemmer           2.1.0                    pypi_0    pypi
sphinx                    3.4.3                    pypi_0    pypi
sphinx-rtd-theme          0.5.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tensorboard               2.3.0              pyh4dce500_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.2.0           gpu_py36hf933387_0  
tensorflow-base           2.2.0           gpu_py36h8a81be8_0  
tensorflow-estimator      2.2.0              pyh208ff02_0  
tensorflow-gpu            2.2.0                h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
torchvision               0.2.1                      py_2    pytorch
tqdm                      4.56.0                   pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.25.11                    py_0  
veriloggen                1.9.1                    pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1             pyhd3eb1b0_0  
wrapt                     1.12.1           py36h7b6447c_1  
xz                        5.2.5                h7b6447c_0  
yarl                      1.6.2            py36h7b6447c_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by Hikaru-Furuta** [comment]
asn1crypto         = 0.24.0
cycler             = 0.10.0
dataclasses        = 0.8
future             = 0.18.2
idna               = 2.6
importlib-metadata = 3.1.1
keyring            = 10.6.0
keyrings.alt       = 3.0
kiwisolver         = 1.3.1
MarkupSafe         = 1.1.1

onnx               = 1.8.0
opencv-python      = 4.5.1.48
pip                = 21.0
protobuf           = 3.14.0
py                 = 1.9.0
pycrypto           = 2.6.1
pygobject          = 3.26.1
pyparsing          = 2.4.7

python-apt       =  1.6.5+ubuntu0.3
python-dateutil  =  2.8.1


pyxdg          =     0.25
SecretStorage  =     2.3.1
torchvision        = 0.8.1
unattended-upgrades = 0.1
veriloggen = 1.8.2


#
matplotlib         = 3.3.3
numpy              = 1.19.4
packaging          = 20.7

pyverilog     = 1.2.1
setuptools      =    39.0.1
six              =   1.11.0
wheel   =   0.30.0
pytest             = 6.1.2

**Comment by RyusukeYamano** [comment]
> FileNotFoundError: Download the YOLOv3 model using Pytorch, such as 'https://github.com/ultralytics/yolov3'. Then extract it, and rename it as 'yolov3'
> 
> Traceback (most recent call last):
> File "darknet_yolov3_tiny.py", line 413, in
> rslt = run(silent=False, verilog_filename='tmp.v')
> File "darknet_yolov3_tiny.py", line 77, in run
> model = models.Darknet(cfg_filename, img_size).to('cpu')
> AttributeError: module 'models' has no attribute 'Darknet'

It seems that the version of that repository 'ultralytics/yolov3' has been upgraded and is no longer supported, so checkout tags/v8 and give it a try.

**Comment by Hikaru-Furuta** [comment]
@RyusukeYamano
Thanks for the replying
I've already tried it but found it wouldn't work causing the same error

**Comment by Hikaru-Furuta** [comment]
File "/home/nel/git/nngen/nngen/onnx/concat.py", line 63, in Concat
    c = operator.scaled_concat(srcs, scales, shamt, axis, name=name)
  File "/home/nel/git/nngen/nngen/operator/normalize.py", line 141, in __init__
    concat.__init__(self, values, axis, dtype, name)
  File "/home/nel/git/nngen/nngen/operator/concat.py", line 56, in __init__
    (size, value.shape[i]))
ValueError: all values must have a same shape, excluding axis: 13 != 26
free(): invalid pointer
Aborted (core dumped)

**Comment by ChristiaanBoe** [comment]
@Hikaru-Furuta 

Have you already tried adding the map in the repository manually, that is how it worked for me.
[yolov3-map-20210215T163716Z-001.zip](https://github.com/NNgen/nngen/files/5982863/yolov3-map-20210215T163716Z-001.zip)

**Comment by Hikaru-Furuta** [comment]
Thank you. I will try that

**Comment by ChristiaanBoe** [comment]
@Hikaru-Furuta 

If it works out, I would appreciate you helping me with or sharing your version of the implementation on the FPGA as this is something I not yet managed to succeed in.
