### ISSUE TITLE
Error Generating model from ONNX

### ISSUE THREAD

**Issue by kanndil** [NNgen/nngen#66]
Given this Onnx file and the following code:

https://drive.google.com/file/d/1h9qmRRbryAZydOmIKnp0HpXJ2PbzyNDB/view?usp=sharing

```

from __future__ import absolute_import
from __future__ import print_function
import os
import sys
import numpy as np
import nngen as ng

# the next line can be removed after installation
sys.path.insert(0, os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))

def run(act_dtype=ng.int8, weight_dtype=ng.int8,
        bias_dtype=ng.int32, scale_dtype=ng.int8,
        with_batchnorm=True, disable_fusion=False,
        conv2d_par_ich=1, conv2d_par_och=1, conv2d_par_col=1, conv2d_par_row=1,
        conv2d_concur_och=None, conv2d_stationary='filter',
        pool_par=1, elem_par=1,
        chunk_size=64, axi_datawidth=32, silent=False,
        onnx_filename='model_final-2.onnx',
        weight_filename='vgg11_imagenet.npz',
        verilog_filename=None,
        sim_filename=None,
        simtype=None,  # no RTL simulation
        # simtype='iverilog',
        # simtype='verilator'
        ):

    # input mean and standard deviation
    imagenet_mean = np.array([0.485, 0.456, 0.406]).astype(np.float32)
    imagenet_std = np.array([0.229, 0.224, 0.225]).astype(np.float32)

    act_shape = (1, 62, 12, 1)

    # ONNX to NNgen
    dtypes = {}
    (outputs, placeholders, variables,
     constants, operators) = ng.from_onnx(onnx_filename,
                                          value_dtypes=dtypes,
                                          default_placeholder_dtype=act_dtype,
                                          default_variable_dtype=weight_dtype,
                                          default_constant_dtype=weight_dtype,
                                          default_operator_dtype=act_dtype,
                                          default_scale_dtype=scale_dtype,
                                          default_bias_dtype=bias_dtype,
                                          disable_fusion=disable_fusion)

    # --------------------
    # (2) Assign quantized weights to the NNgen operators
    # --------------------

    if act_dtype.width > 8:
        act_scale_factor = 128
    else:
        act_scale_factor = int(round(2 ** (act_dtype.width - 1) * 0.5))

    input_scale_factors = {'act': act_scale_factor}
    input_means = {'act': imagenet_mean * act_scale_factor}
    input_stds = {'act': imagenet_std * act_scale_factor}

    ng.quantize(outputs, input_scale_factors, input_means, input_stds)


if __name__ == '__main__':
    rslt = run(silent=False, verilog_filename='tmp.v')
    print(rslt)

```

I get the following error 

```
Youssefs-MacBook-Pro-9:nngen youssef$ python3 kws_onnx_nngen.py 
Traceback (most recent call last):
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/kws_onnx_nngen.py", line 392, in <module>
    rslt = run(silent=False, verilog_filename='tmp.v')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/kws_onnx_nngen.py", line 72, in run
    constants, operators) = ng.from_onnx(onnx_filename,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/onnx/__init__.py", line 329, in from_onnx
    visitor.visit(name)
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/onnx/__init__.py", line 147, in visit
    node_op = node_func(self, node)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/onnx/gemm.py", line 63, in Gemm
    reshape_value = filter.value.reshape(shape)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Here is the architecture of the used model. 

![model_final onnx](https://github.com/NNgen/nngen/assets/63082375/b09f3e47-4304-433e-a10d-fa53e87de955)

**Comment by kanndil** [comment]
I also tried writing the model myself using NNGen APIs, however I keep getting a similar error in the quantization step. Here is a code snnipit:

```
from __future__ import absolute_import
from __future__ import print_function

import sys
import os

import nngen as ng


# --------------------
# (1) Represent a DNN model as a dataflow by NNgen operators
# --------------------

# data types
act_dtype = ng.int8
weight_dtype = ng.int8
bias_dtype = ng.int32
scale_dtype = ng.int8
batchsize = 1  # Change as per your batch size

# input
input_layer = ng.placeholder(dtype=act_dtype,
                             shape=(batchsize, 62, 12, 3),  # N, H, W, C
                             name='input_layer')

# layer 0: conv2d (with bias and scale (= batchnorm)), relu, max_pool
w0 = ng.variable(dtype=weight_dtype,
                 shape=(16, 3, 3, 3),  # Och, Ky, Kx, Ich
                 name='w0')
b0 = ng.variable(dtype=bias_dtype,
                 shape=(w0.shape[0],), name='b0')
s0 = ng.variable(dtype=scale_dtype,
                 shape=(w0.shape[0],), name='s0')

a0 = ng.conv2d(input_layer, w0,
               strides=(1, 1, 1, 1),
               bias=b0,
               scale=s0,
               act_func=ng.relu,
               dtype=act_dtype,
               sum_dtype=ng.int32)

a0p = ng.max_pool_serial(a0,
                         ksize=(1, 2, 1, 1),
                         strides=(1, 2, 1, 1))

# layer 1: conv2d, relu, max_pool
w1 = ng.variable(weight_dtype,
                 shape=(32, 3, 3, a0p.shape[-1]),
                 name='w1')
b1 = ng.variable(bias_dtype,
                 shape=(w1.shape[0],),
                 name='b1')
s1 = ng.variable(scale_dtype,
                 shape=(w1.shape[0],),
                 name='s1')

a1 = ng.conv2d(a0p, w1,
               strides=(1, 1, 1, 1),
               bias=b1,
               scale=s1,
               act_func=ng.relu,
               dtype=act_dtype,
               sum_dtype=ng.int32)

a1p = ng.max_pool_serial(a1,
                         ksize=(1, 2, 1, 1),
                         strides=(1, 2, 1, 1))

# layer 2: conv2d, relu, dropout
w2 = ng.variable(weight_dtype,
                 shape=(64, 3, 3, a1p.shape[-1]),
                 name='w2')
b2 = ng.variable(bias_dtype,
                 shape=(w2.shape[0],),
                 name='b2')
s2 = ng.variable(scale_dtype,
                 shape=(w2.shape[0],),
                 name='s2')

a2 = ng.conv2d(a1p, w2,
               strides=(1, 1, 1, 1),
               bias=b2,
               scale=s2,
               act_func=ng.relu,
               dtype=act_dtype,
               sum_dtype=ng.int32)


a2p = ng.max_pool_serial(a2,
                         ksize=(1, 2, 1, 1),
                         strides=(1, 2, 1, 1))


# layer 3: conv2d, relu, dropout
w3 = ng.variable(weight_dtype,
                 shape=(32, 3, 3, a2.shape[-1]),
                 name='w3')
b3 = ng.variable(bias_dtype,
                 shape=(w3.shape[0],),
                 name='b3')
s3 = ng.variable(scale_dtype,
                 shape=(w3.shape[0],),
                 name='s3')

a3 = ng.conv2d(a2p, w3,
               strides=(1, 1, 1, 1),
               bias=b3,
               scale=s3,
               act_func=ng.relu,
               dtype=act_dtype,
               sum_dtype=ng.int32)

# flatten layer
a3_flat = ng.reshape(a3, [batchsize, -1])

# dense layer
w4 = ng.variable(weight_dtype,
                 shape=(35, a3_flat.shape[-1]),  # 'type' is the number of classes
                 name='w4')
b4 = ng.variable(bias_dtype,
                 shape=(w4.shape[0],),
                 name='b4')
s4 = ng.variable(scale_dtype,
                 shape=(w4.shape[0],),
                 name='s4')

output_layer = ng.matmul(a3_flat, w4,
                         bias=b4,
                         scale=s4,
                         transposed_b=True,
                         name='output_layer',
                         dtype=act_dtype,
                         sum_dtype=ng.int32)

## softmax output
#output_layer = ng.softmax(output_layer, name='softmax_output', dtype=act_dtype)


# --------------------
# (2) Assign weights to the NNgen operators
# --------------------

# In this example, random floating-point values are assigned.
# In a real case, you should assign actual weight values
# obtianed by a training on DNN framework.

# If you don't you NNgen's quantizer, you can assign integer weights to each tensor.
print("Shape after layer 0:", a0.shape)
print("Shape after layer 1:", a1.shape)
print("Shape after layer 2:", a2.shape)
print("Shape after layer 3:", a3.shape)
print("Shape after flatten:", a3_flat.shape)
print("Shape after dense:", output_layer.shape)


import numpy as np

# --------------------
# Assign weights to the NNgen operators
# --------------------

# Layer 0: conv2d, relu, max_pool
w0_value = np.random.normal(size=w0.length).reshape(w0.shape)
w0_value = np.clip(w0_value, -3.0, 3.0)
w0.set_value(w0_value)

b0_value = np.random.normal(size=b0.length).reshape(b0.shape)
b0_value = np.clip(b0_value, -3.0, 3.0)
b0.set_value(b0_value)

s0_value = np.ones(s0.shape)
s0.set_value(s0_value)

# Layer 1: conv2d, relu, max_pool
w1_value = np.random.normal(size=w1.length).reshape(w1.shape)
w1_value = np.clip(w1_value, -3.0, 3.0)
w1.set_value(w1_value)

b1_value = np.random.normal(size=b1.length).reshape(b1.shape)
b1_value = np.clip(b1_value, -3.0, 3.0)
b1.set_value(b1_value)

s1_value = np.ones(s1.shape)
s1.set_value(s1_value)

# Layer 2: conv2d, relu
w2_value = np.random.normal(size=w2.length).reshape(w2.shape)
w2_value = np.clip(w2_value, -3.0, 3.0)
w2.set_value(w2_value)

b2_value = np.random.normal(size=b2.length).reshape(b2.shape)
b2_value = np.clip(b2_value, -3.0, 3.0)
b2.set_value(b2_value)

s2_value = np.ones(s2.shape)
s2.set_value(s2_value)

# Layer 3: conv2d, relu

w3_value = np.random.normal(size=w3.length).reshape(w3.shape)
w3_value = np.clip(w3_value, -3.0, 3.0)
w3.set_value(w3_value)

b3_value = np.random.normal(size=b3.length).reshape(b3.shape)
b3_value = np.clip(b3_value, -3.0, 3.0)
b3.set_value(b3_value)

s3_value = np.ones(s3.shape)
s3.set_value(s3_value)

# Dense layer: full-connection

w4_value = np.random.normal(size=w4.length).reshape(w4.shape)
w4_value = np.clip(w4_value, -3.0, 3.0)
w4.set_value(w4_value)
#print("here**************************", "b4.length", b4.length ,"b4.shape:", b4.shape)
b4_value = np.random.normal(size=b4.length).reshape(b4.shape)
b4_value = np.clip(b4_value, -3.0, 3.0)
b4.set_value(b4_value)

s4_value = np.ones(s4.shape)
s4.set_value(s4_value)

print("here**************************", "b0.length", b0.length ,"b0.shape:", b0.shape)
print("here**************************", "b1.length", b1.length ,"b1.shape:", b1.shape)
print("here**************************", "b2.length", b2.length ,"b2.shape:", b2.shape)
print("here**************************", "b3.length", b3.length ,"b3.shape:", b3.shape)
print("here**************************", "b4.length", b4.length ,"b4.shape:", b4.shape)

print("\n\n")

print("here**************************", "w0.length", w0.length ,"w0.shape:", w0.shape)
print("here**************************", "w1.length", w1.length ,"w1.shape:", w1.shape)
print("here**************************", "w2.length", w2.length ,"w2.shape:", w2.shape)
print("here**************************", "w3.length", w3.length ,"w3.shape:", w3.shape)
print("here**************************", "w4.length", w4.length ,"w4.shape:", w4.shape)

print("\n\n")

# --------------------
# Quantizing the floating-point weights by the NNgen quantizer
# --------------------

imagenet_mean = np.array([0.485, 0.456, 0.406]).astype(np.float32)
imagenet_std = np.array([0.229, 0.224, 0.225]).astype(np.float32)

if act_dtype.width > 8:
    act_scale_factor = 128
else:
    act_scale_factor = int(round(2 ** (act_dtype.width - 1) * 0.5))


print("act_scale_factor:", act_scale_factor)
input_scale_factors = {'input_layer': act_scale_factor}
input_means = {'input_layer': imagenet_mean * act_scale_factor}
input_stds = {'input_layer': imagenet_std * act_scale_factor}

ng.quantize([output_layer], input_scale_factors, input_means, input_stds)

```



Here is the error I get:

```
Youssefs-MacBook-Pro-9:nngen youssef$ python3 KWS_nngen.py 
Shape after layer 0: (1, 62, 12, 16)
Shape after layer 1: (1, 31, 12, 32)
Shape after layer 2: (1, 16, 12, 64)
Shape after layer 3: (1, 8, 12, 32)
Shape after flatten: (1, 3072)
Shape after dense: (1, 35)
here************************** b0.length 16 b0.shape: (16,)
here************************** b1.length 32 b1.shape: (32,)
here************************** b2.length 64 b2.shape: (64,)
here************************** b3.length 32 b3.shape: (32,)
here************************** b4.length 35 b4.shape: (35,)



here************************** w0.length 432 w0.shape: (16, 3, 3, 3)
here************************** w1.length 4608 w1.shape: (32, 3, 3, 16)
here************************** w2.length 18432 w2.shape: (64, 3, 3, 32)
here************************** w3.length 18432 w3.shape: (32, 3, 3, 64)
here************************** w4.length 107520 w4.shape: (35, 3072)



act_scale_factor: 64
<nngen.quantizer._QuantizeVisitor object at 0x1053378f0> <_lazy_reshape None dtype:int8 shape:(1, 3072) default_addr:0() scale_factor:1.000000>
Traceback (most recent call last):
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/KWS_nngen.py", line 277, in <module>
    ng.quantize([output_layer], input_scale_factors, input_means, input_stds)
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/quantizer/__init__.py", line 276, in quantize
    visitor.visit(output)
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/quantizer/__init__.py", line 158, in visit
    node_func(self, node)
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/quantizer/matmul.py", line 11, in matmul
    return conv2d.conv2d(visitor, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/quantizer/conv2d.py", line 112, in conv2d
    q_rshift_mul, q_rshift_sum, q_rshift_out = find_optimal_rshift(
                                               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/quantizer/conv2d.py", line 157, in find_optimal_rshift
    input = node.args[0].eval(visitor.memo, visitor.input_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youssef/Documents/Work/AUC_Open_Hardware_Lab/nngen/nngen/basic_types.py", line 2576, in eval
    return np.reshape(arg, [-1] + list(self.shape[1:]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 23808 into shape (3072)
```
